import { motion } from 'framer-motion'
import { ArrowRight, Check, ChevronDown, Clock3, Heart, HeartHandshake, Leaf, MessageCircle, Phone, Star, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import Footer from '../components/layout/Footer'
import Navbar from '../components/layout/Navbar'
import { CONTACT_CONFIG, emailHref, primaryPhoneHref, whatsappHref } from '../config/contactConfig'
import { benefits, challenges, faqs, journeySteps, services, solutionServices, testimonials } from '../data/siteData'

const reveal = { hidden: { opacity: 0, y: 22 }, visible: { opacity: 1, y: 0, transition: { duration: .55 } } }

export default function LandingPage() {
  return <div className="site-page"><Navbar /><main>
    <section className="hero-section"><div className="hero-content"><motion.div initial="hidden" animate="visible" variants={reveal}><p className="eyebrow"><Leaf size={14} /> A human touch in healthcare <Leaf size={14} /></p><h1>Your Healthcare<br />Journey,<br /><em>We're With You.</em></h1><p className="hero-description">From the first question to ongoing support, CareBridge helps you navigate healthcare with confidence.</p><div className="hero-actions"><Link className="primary-button" to="/medical-saathi">Start Your Journey <ArrowRight size={17} /></Link><a className="outline-button" href={primaryPhoneHref}><Phone size={17} /> Talk to a Care Coordinator</a></div><div className="hero-trust"><span><Check size={14} /> Trusted support</span><span><Check size={14} /> Personalized guidance</span><span><Check size={14} /> Always here for you</span></div></motion.div></div><HeroVisual /></section>
    <section className="benefit-strip">{benefits.map(({ title, text, icon: Icon }) => <motion.div whileHover={{ y: -5 }} className="benefit-card" key={title}><span className="soft-icon"><Icon size={23} /></span><span><strong>{title}</strong><small>{text}</small></span></motion.div>)}</section>
    <section className="split-section challenge-section" id="challenge"><motion.div initial="hidden" whileInView="visible" viewport={{ once: true }} variants={reveal}><p className="eyebrow">The challenge</p><h2>Healthcare Isn't Just<br />About Finding a Doctor.</h2><p>Sometimes the hardest part is knowing what to do next. The healthcare journey can be confusing and overwhelming.</p><Link className="text-link" to="/medical-saathi">You're Not Alone <ArrowRight size={15} /></Link></motion.div><div className="challenge-grid">{challenges.map(([text, Icon]) => <motion.div whileHover={{ y: -4 }} className="mini-card" key={text}><span className="mini-icon"><Icon size={22} /></span><strong>{text}</strong><ArrowRight size={15} /></motion.div>)}</div></section>
    <section className="split-section solution-section" id="solution"><div className="solution-orbit"><div className="orbit-ring ring-one" /><div className="orbit-ring ring-two" /><div className="solution-core"><HeartHandshake size={35} /><strong>CareBridge</strong><small>One support system</small></div>{solutionServices.map(([text, Icon], index) => <div className={`orbit-node node-${index + 1}`} key={text}><Icon size={19} /><span>{text}</span></div>)}</div><motion.div initial="hidden" whileInView="visible" viewport={{ once: true }} variants={reveal}><p className="eyebrow">Our solution</p><h2>Meet <em>CareBridge.</em></h2><h3>A human support system for your healthcare journey.</h3><p>CareBridge helps patients and families navigate healthcare options, coordinate next steps and stay supported throughout their journey.</p><Link className="primary-button small-button" to="/medical-saathi">Learn More About CareBridge <ArrowRight size={16} /></Link></motion.div></section>
    <section className="journey-section" id="journey"><div className="section-heading"><p className="eyebrow">The CareBridge journey</p><h2>From Concern to Complete Care</h2><p>We simplify your healthcare journey with human support at every step.</p></div><div className="journey-track">{journeySteps.map(([title, text], index) => <div className="journey-step" key={title}><span className="step-number">0{index + 1}</span><div className="step-icon">{index === 0 ? <Users size={21} /> : index === 1 ? <HeartHandshake size={21} /> : <Check size={21} />}</div><strong>{title}</strong><small>{text}</small></div>)}</div></section>
    <section className="services-section" id="services"><div className="section-heading row-heading"><div><p className="eyebrow">Our services</p><h2>Comprehensive Support for Your Healthcare Journey</h2><p>From finding the right specialist to recovery support, we're with you every step.</p></div><Link className="outline-button" to="/medical-saathi">View All Services <ArrowRight size={16} /></Link></div><div className="service-grid">{services.map(([title, text, Icon]) => <motion.div whileHover={{ y: -5 }} className="service-card" key={title}><span className="service-icon"><Icon size={23} /></span><span><strong>{title}</strong><small>{text}</small></span><ArrowRight size={16} /></motion.div>)}</div></section>
    <section className="support-banner"><div className="support-clock"><Clock3 size={40} /><strong>24/7</strong></div><div><h2>Support When You Need Someone Beside You.</h2><p>Healthcare journeys don't always happen during convenient hours. CareBridge is designed around patient support and coordination whenever help is needed.</p><div className="support-points"><span><Check size={14} /> 24/7 Assistance</span><span><Check size={14} /> Home Care Coordination</span><span><Check size={14} /> Nursing Support</span><span><Check size={14} /> Recovery Support</span></div><div className="support-contact"><a href={primaryPhoneHref}><Phone size={14} /> {CONTACT_CONFIG.primaryPhone}</a><a href={emailHref}><MessageCircle size={14} /> {CONTACT_CONFIG.email}</a></div></div><Link className="primary-button" to="/medical-saathi">Get 24/7 Support <ArrowRight size={16} /></Link></section>
    <section className="stories-section"><div className="section-heading"><p className="eyebrow">What people say (example testimonials)</p><h2>Stories of Support and Care</h2></div><div className="testimonial-grid">{testimonials.map(([quote, name, role]) => <div className="testimonial-card" key={name}><MessageCircle size={25} /><p>{quote}</p><div className="stars">{[1, 2, 3, 4, 5].map((star) => <Star fill="currentColor" size={14} key={star} />)}</div><strong>{name}</strong><small>{role}</small></div>)}</div></section>
    <section className="bottom-cta"><div><p className="eyebrow">Medical Saathi</p><h2>Tell Us What You're Going Through.</h2><p>Share a few details and our care team can understand how we may assist you.</p><Link className="primary-button" to="/medical-saathi">Request Healthcare Assistance <ArrowRight size={17} /></Link><div className="cta-contact"><a href={whatsappHref('Hello Medical Saathi, I would like healthcare support. Please assist me.')}><MessageCircle size={15} /> Chat on WhatsApp</a><a href={emailHref}><MessageCircle size={15} /> Email Medical Saathi</a></div></div><div className="cta-art"><Heart size={100} /></div></section>
    <FAQSection />
  </main><Footer /></div>
}

function HeroVisual() {
  return <div className="hero-visual"><div className="hero-glow" /><div className="people-illustration"><div className="person person-care"><span className="head" /><span className="body" /></div><div className="person person-patient"><span className="head" /><span className="body" /></div><HeartHandshake className="connection-heart" size={34} /></div><div className="handwritten">Not just a service,<br />A companion in<br />your care journey <Heart size={14} /></div><div className="stat-card stat-top"><Clock3 size={22} /><span><strong>24/7</strong><small>Patient Support</small></span></div><div className="stat-card stat-bottom"><Users size={22} /><span><strong>10K+</strong><small>Patients Supported</small></span></div><div className="plant plant-one" /><div className="plant plant-two" /></div>
}

function FAQSection() {
  return <section className="faq-section"><div className="section-heading"><p className="eyebrow">Have questions?</p><h2>Frequently Asked Questions</h2></div><div className="faq-list">{faqs.map(([question, answer], index) => <details key={question} open={index === 0}><summary>{question}<ChevronDown size={18} /></summary><p>{answer}</p></details>)}</div></section>
}
